name: Client CI

on:
    pull_request:
        branches:
            - 'main'
        paths:
            - 'client/**'
            - '.github/workflows/client-ci.yaml'
    push:
        branches:
            - '**'
        paths:
            - 'client/**'
            - '.github/workflows/client-ci.yaml'

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: client

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: Install dependencies
              run: npm ci

            - name: Run Linter
              run: npm run lint

            - name: Run Formatter
              run: npm run format

            - name: Run Tests
              run: npm run test

            - name: Run build
              run: npm run build